export class AppInfo {
  static readonly APP_NAME: string = 'MilkTea';
  static readonly PROJECT_NAME: string = 'MilkTea ArkTS';
  static readonly AUTHOR: string = 'Liu Yuping';
  static readonly VERSION: string = '1.0.0';
  static readonly BUILD_ID: string = 'milktea-20260620-001';
  static readonly BUNDLE_NAME: string = 'com.liuyuping.milktea';
  static readonly GITHUB: string = 'https://github.com/fplity/MilkTea-ArkTS';
}